### ISSUE TITLE
SHIFT and CTRL  are not optional with mouse drag

### ISSUE THREAD

**Issue by shobhitg** [fibo/three-orbitcontrols#10]
Hi,

Is there a way I could disable the shift key?

I would like to do the regular orbital rotation on the mouse drag even when the shift key or the control key is pressed.

The use case is that I need to use `shift` for some other keyboard `wasd` interactions, and don't wish the Mouse movement experience to change.

Thanks for help.

**Comment by fibo** [comment]
Hi,

probably you need to add `event.stopPropagation()` on your event handler.

**Comment by shobhitg** [comment]
I am not sure how that will work, both `orbital-controls` and my code are listening to the same dom element (canvas).

**Comment by fibo** [comment]
Please notice that this repository goal is to package the OrbitControl.js and there is no coelde implementation. You should open an issue on three.j repo or feel free to fork this repo and use a custom version of OrbitControl according to your needs.
