### ISSUE TITLE
CHANGELOG.md is needed

### ISSUE THREAD

**Issue by drac** [fibo/three-orbitcontrols#11]
It would be so much better if we had a CHANGELOG file to make it easier for users and contributors to see precisely what notable changes have been made between each release.

**Comment by fibo** [comment]
Hi @drac I agre it si good ti have a changelog in general for users, however in this repo there will be no contributors cause it just distribute the OrbitControls.js file.

There are few chances you can find changelog info related to OrbitControls.js in [official three.js release page](https://github.com/mrdoob/three.js/releases), in me opinion the best option is to read [OrbitControls.js](https://github.com/mrdoob/three.js/commits/master/examples/js/controls/OrbitControls.js) history. Thanks to your tip, I am adding that link to the Readme.

Please Aldo notice that major version in this repo follows three.js release number.

**Comment by drac** [comment]
In that case, you are right - no need for a CHANGELOG.

@fibo thank you for the information. 
Cheers.
