### ISSUE TITLE
2.110.1版本，点击canvas会有蓝色边框出现

### ISSUE THREAD

**Issue by feidudu1** [fibo/three-orbitcontrols#12]
![image](https://user-images.githubusercontent.com/16274956/69403946-e899a580-0d36-11ea-877a-8a6f75da1186.png)

2.102.1版本没有这个问题

**Comment by fibo** [comment]
Please open an issue on [Threejs repository](https://github.com/mrdoob/three.js/).

This repo is only a distributor of OrbitControls.js
