### ISSUE TITLE
Cannot add property OrbitControls

### ISSUE THREAD

**Issue by pepelxD** [fibo/three-orbitcontrols#4]
When I try to use it as a module, I get the following error

> Cannot add property OrbitControls, object is not extensible

**Comment by fibo** [comment]
Can you provide more info, like a link to your code or report it here in this issue?

I tryed latest version of three-orbitcontrols in [tris3d-canvas](http://g14n.info/tris3d-canvas/) package and it worked for me.

**Comment by fibo** [comment]
@pepelxD can you add more info in order to understand your issue? I am going to close it, if you still have problems, feel free to open a new one.
