### ISSUE TITLE
TypeScript compilation error

### ISSUE THREAD

**Issue by avatsaev** [fibo/three-orbitcontrols#7]
Version: 2.96.1
TypeScript: 2.7.2

Usage (can't use require() in TS):

```
import * as OrbitControls from 'three-orbitcontrols';
```

```
this.controls = new OrbitControls(this.camera, this.renderer.domElement);
```

Error:

```
 error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

```

When omitting `new`, a run time error occurs:

```
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at HTMLCanvasElement.onMouseDown (OrbitControls.js:730)
```

**Comment by fibo** [comment]
Thank you for reporting it. Any hint on how to solve it? Yesterday I accepted a PR and trusted it worked (my fault). I was excited about the idea of adding TS support and I started to use TS few weeks ago in another project. Honestly I do not know the solution right now, will fix as soon as I can.

**Comment by fibo** [comment]
I fixed it and added an [examples/](https://github.com/fibo/three-orbitcontrols/tree/master/examples) folder where there is a TypeScript code I checked it works.

Just relesead a patch on npm, `v2.96.2` should work with TypeScript now, thanks again for reporting it.
