### ISSUE TITLE
http://tris3d.net/ not Working

### ISSUE THREAD

**Issue by waqast** [fibo/three-orbitcontrols#9]
Only a blank page with 3 menu buttons at bottom.

Following is the error in console:

bundle.js:8383 Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in div (created by HeroBody)
    in HeroBody (created by Root)
    in section (created by Hero)
    in Hero (created by Root)
    in Root (created by Connect(Root))
    in Connect(Root)
    in Provider

**Comment by fibo** [comment]
@waqast thanks, I updated link with a working one.
